version: "3"
services:
  web:
    build: .
    command: sh ./entry_points/local.sh
    volumes:
      - .:/api
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    env_file:
      - ./environments/local.env
    links:
      - db
  db:
    image: postgres
    env_file:
      - ./environments/local.env

