version: "3"
services:
  web:
    build: .
    command: sh run.sh
    volumes:
      - .:/api
    ports:
      - "3000:3000"
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD
    env_file:
      - .env
