version: "3"
services:
  api:
    build: .
    command: sh run.sh
    volumes:
      - .:/api
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD
    env_file:
      - .env
  db:
    image: "mysql:5"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD
      - MYSQL_DATABASE=root
